"""
Domain enums and value objects.

Pure Python — no FastAPI or SQLAlchemy imports.
These represent business concepts shared across layers.
"""

import enum


class CoachPersonality(str, enum.Enum):
    """
    AI coach personality types.

    Each personality changes coaching *strategy*, not just tone.
    Stored on user profile and passed to Coach Agent (Step 7).
    """

    TEACHER = "teacher"           # 선생님형 — structured lessons, step-by-step
    FRIEND = "friend"             # 친구형 — casual encouragement
    PASSION = "passion"           # 열정 코치형 — high energy, motivational
    DATA_ANALYST = "data_analyst" # 데이터 분석형 — metrics-driven feedback
    CEO = "ceo"                   # CEO형 — strategic, outcome-focused
    TSUNDERE = "tsundere"         # 츤데레형 — tough love with hidden care


class GoalStatus(str, enum.Enum):
    """Lifecycle status of a user goal."""

    ACTIVE = "active"
    COMPLETED = "completed"
    PAUSED = "paused"
    ABANDONED = "abandoned"


class PlanType(str, enum.Enum):
    """Planning horizon — generated by Planner Agent (Step 6–7)."""

    MONTHLY = "monthly"
    WEEKLY = "weekly"
    DAILY = "daily"


class MissionStatus(str, enum.Enum):
    """Daily mission completion state."""

    PENDING = "pending"
    COMPLETED = "completed"
    FAILED = "failed"
    SKIPPED = "skipped"


class ExecutionStatus(str, enum.Enum):
    """Outcome of a logged execution attempt."""

    SUCCESS = "success"
    FAILURE = "failure"


class TimelineEventType(str, enum.Enum):
    """Categories for growth timeline entries."""

    GOAL_CREATED = "goal_created"
    GOAL_COMPLETED = "goal_completed"
    MISSION_COMPLETED = "mission_completed"
    MISSION_FAILED = "mission_failed"
    MILESTONE = "milestone"
    REFLECTION = "reflection"
    SCORE_UPDATE = "score_update"
